openapi: "3.0.0"
info:
  title: "LogSlice"
  description: "エラーメッセージに関するナレッジベースを提供するAPI"
  version: "0.0.1"
servers:
  - url: "http://localhost:8000"
paths:
  /query:
    post:
      summary: "エラーメッセージを問い合わせる"
      description: "エラーメッセージに関する質問を受け付けます"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                logs:
                  type: array
                  items:
                    type: string
      responses:
        200:
          description: "正常な応答"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "OK"
                  summary:
                    type: string
                    example: "404 Not Foundの意味"
                  description:
                    type: string
                    example: "リクエスト対象が存在しないことを意味します。"
                  next_you_can:
                    type: array
                    items:
                      type: object
                      properties:
                        summary:
                          type: string
                          example: "リクエストURLが間違えていないか確認する"
                        description:
                          type: string
                          example: "リクエストURLが間違えていないか確認してください。"
                        commands:
                          type: array
                          items:
                            type: object
                            properties:
                              language:
                                type: string
                                example: "bash"
                              on:
                                type: string
                                example: "shell"
                              command:
                                type: string
                                example: "ls -l /path/to/target"
        400:
          description: "エラー応答"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Bad Request"
                  summary:
                    type: string
                    example: "エラーメッセージではありません。"